fn main() {
    // why: sqlx::migrate!() embeds the migrations at compile time, but a
    // proc macro can't ask the compiler to watch a directory — a new .sql
    // file alone rebuilt nothing, and the app kept the old migration set.
    // sqlx's docs prescribe exactly this line for stable Rust.
    println!("cargo:rerun-if-changed=migrations");
    // why an app manifest: without one, Tauri lets every window call every
    // registered command, and the capability files only govern plugins.
    // Declaring the commands makes each one a permission (allow-<name>) that
    // a window must be granted in capabilities/ — see main.json,
    // settings.json and compose.json for who gets what.
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("tauri-build failed");
}

/// Every command in lib.rs's `generate_handler!`, in the same order. A
/// command missing here is callable from no window at all (deny by default);
/// `lib.rs`'s tests keep the two lists in step.
const APP_COMMANDS: &[&str] = &[
    "list_accounts",
    "add_account",
    "oauth_providers",
    "add_oauth_account",
    "cancel_oauth_sign_in",
    "reconnect_account",
    "delete_account",
    "set_account_color",
    "list_contacts",
    "list_mailboxes",
    "list_messages",
    "view_status",
    "list_thread",
    "search_messages",
    "sync_account",
    "refresh_account",
    "set_message_read",
    "move_to_trash",
    "archive_message",
    "move_message",
    "move_messages",
    "trash_messages",
    "archive_messages",
    "set_messages_read",
    "trash_thread",
    "archive_thread",
    "move_thread",
    "get_message_body",
    "get_message_quote",
    "thread_bodies",
    "inspect_attachments",
    "save_attachment",
    "save_all_attachments",
    "attachment_preview",
    "queue_send",
    "undo_send",
    "schedule_send",
    "list_scheduled",
    "send_scheduled_now",
    "cancel_scheduled",
    "save_draft",
    "discard_draft",
    "open_draft",
    "test_connection",
    "open_compose",
    "take_compose_draft",
    "close_compose",
    "open_settings",
    "close_settings",
    "get_remote_image_policy",
    "set_remote_image_policy",
    "get_avatar_lookup_enabled",
    "set_avatar_lookup_enabled",
    "load_domain_avatars",
    "get_llm_summary_enabled",
    "set_llm_summary_enabled",
    "llm_status",
    "set_llm_model",
    "get_llm_summary_language",
    "set_llm_summary_language",
    "download_llm_model",
    "cancel_llm_download",
    "remove_llm_model",
    "summarize_message",
    "summarize_thread",
    "cancel_summary",
    "cached_summary",
    "get_notification_settings",
    "set_notification_settings",
    "set_account_notifications",
    "preview_notification_sound",
    "get_swipe_actions",
    "set_swipe_actions",
    "get_shortcuts",
    "set_shortcut",
    "reset_shortcuts",
    "timing_enabled",
    "log_timing",
    "get_appearance",
    "set_appearance",
    "get_thread_order",
    "set_thread_order",
    "get_date_time_format",
    "set_date_time_format",
    "list_signatures",
    "create_signature",
    "update_signature",
    "delete_signature",
    "set_signature_accounts",
    "list_aliases",
    "add_alias",
    "update_alias",
    "delete_alias",
    "set_default_alias",
];
